### ISSUE TITLE
Different "spaces" for giwyn

### ISSUE THREAD

**Issue by calve** [k0pernicus/giwyn#1]
Hi

In order to manage multiple giwyn spaces, it should follow the same discovery path as git, that is :
- if there is a `.git` file in the current working directory, use it
- if not, look for the `.git` file in the parent directory
- repeat until mount point 

Also, I expected this file to be called `.giwyn` :)

**Comment by k0pernicus** [comment]
Hi!

Thanks for the comment :-)

So, you think it's important to discover git projects from the current working directory to your home root directory, and not the reverse? As you said, there is only a part of your home directory discovered, not all of those...
But i can implement the thing and make the decision to the user : just discover a small part of his drive from the current working directory, or all the home directory (to not miss some hiddent git projects...).

For the second part, it's on the road :-)

The 0.4 version is coming ;-)
